---

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: 'install cramfs /bin/true'
    state: present
    create: true
  tags:
  - Level 1 - Server
  - Level 1 - Workstation

- name: 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
  modprobe:
    name: cramfs
    state: absent

- name: 1.1.1.2 Ensure mounting of freevxfs filesystem is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: 'install freevxfs /bin/true'
    state: present
    create: true
  tags:
  - Level 1 - Server
  - Level 1 - Workstation

- name: 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled
  modprobe:
    name: freevxfs
    state: absent
  tags:
  - Level 1 - Server
  - Level 1 - Workstation

- name: 1.1.1.3 Ensure mounting of jffs2 filesystem is disabled
  lineinfile:
    path: /etc/modprobe.d/CIS.conf
    line: 'install jffs2 /bin/true'
    state: present
    create: true
  tags:
  - Level 1 - Server
  - Level 1 - Workstation

- name: 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled
  modprobe:
    name: jffs2
    state: absent
  tags:
  - Level 1 - Server
  - Level 1 - Workstation


# These could probably be done in a loop? Rebuild with these additional filesystems:
#
# squashfs
# hfs
# hfsplus
# udf
# vfat
# 

# Ensure separate partition exists for:
#
# /tmp
# /var
# /var/tmp
# /var/log
# /var/log/audit
# /home


# 1.1.3 Ensure nodev option set on /tmp partition

# 1.1.4 Ensure nosuid option set on /tmp partition

# 1.1.5 Ensure noexec option set on /tmp partition 

# 1.1.8 Ensure nodev option set on /var/tmp partition

# 1.1.9 Ensure nosuid option set on /var/tmp partition

# 1.1.10 Ensure noexec option set on /var/tmp partition

# 1.1.14 Ensure nodev option set on /home partition

# 1.1.15 Ensure nodev option set on /dev/shm partition

# 1.1.16 Ensure nosuid option set on /dev/shm partition

# 1.1.17 Ensure noexec option set on /dev/shm partition

# 1.1.21 Ensure sticky bit is set on all world-writable directories

# 1.1.22 Disable Automounting


## 1.2 Configure Software Updates
# 1.2.3 Ensure gpgcheck is globally activated

## 1.3
# 1.3.1 Ensure AIDE is installed 

# 1.3.2 Ensure filesystem integrity is regularly checked

## 1.4 Filesystem Integrity
# 1.4.1 Ensure permissions on bootloader config are configured

# 1.4.2 Ensure bootloader password is set

# 1.4.3 Ensure authentication required for single user mode

## 1.5Additional Process Hardening 
# 1.5.1 Ensure core dumps are restricted

# 1.5.3 Ensure address space layout randomization (ASLR) is enabled 

# 1.5.4 Ensure prelink is disabled

## 1.6 Mandatory Access Controll
# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration 

# 1.6.1.2 Ensure the SELinux state is enforcing

# 1.6.1.3 Ensure SELinux policy is configured

# 1.6.1.4 Ensure SETroubleshoot is not installed 

# 1.6.1.5 Ensure the MCS Translation Service (mcstrans) is not installed 

# 1.6.1.6 Ensure no unconfined daemons exist

# 1.6.2 Ensure SELinux is installed 

## 1.7 Warning Banners
# 1.7.1.1 Ensure message of the day is configured properly

# 1.7.1.2 Ensure local login warning banner is configured properly

# 1.7.1.3 Ensure remote login warning banner is configured properly

# 1.7.1.4 Ensure permissions on /etc/motd are configured

# 1.7.1.5 Ensure permissions on /etc/issue are configured

# 1.7.1.6 Ensure permissions on /etc/issue.net are configured

# 1.7.2 Ensure GDM login banner is configured

## 1.8 Security updates
# 1.8 Ensure updates, patches, and additional security software are installed