---

## 2.1 Inetd Services

- name: 2.1.1 Ensure chargen services are not enabled 
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - chargen-dgram
    - chargen-stream

- name: 2.1.2 Ensure daytime services are not enabled
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - daytime-dgram
    - daytime-stream

- name: 2.1.3 Ensure discard services are not enabled
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - discard-dgram
    - discard-stream

- name: 2.1.4 Ensure echo services are not enabled
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - echo-dgram
    - echo-stream

- name: 2.1.5 Ensure time services are not enabled 
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - time-dgram
    - time-stream

- name: 2.1.6 Ensure tftp server is not enabled
  service:
    name: tftp
    state: stopped
    enabled: false

- name: 2.1.7 Ensure xinetd is not enabled
  service:
    name: xinetd
    state: stopped
    enabled: false

## 2.2 Special Purpose Services

## 2.2.1 Time Synchronization

# 2.2.1.1 Ensure time synchronization is in use


# 2.2.1.2 Ensure ntp is configured 


# 2.2.1.3 Ensure chrony is configured


# Interesting tip from CIS: Use At Least Two Synchronized Time Sources For All Servers And Network Equipment 

## 2.2.2 Ensure X Window System is not installed

- name: 2.2.3 Ensure Avahi Server is not enabled
  service:
    name: avahi-daemon
    state: stopped
    enabled: false
    
- name: 2.2.4 Ensure CUPS is not enabled
  service:
    name: cups
    state: stopped
    enabled: false

- name: 2.2.5 Ensure DHCP Server is not enabled
  service:
    name: dhcpd
    state: stopped
    enabled: false

- name: 2.2.6 Ensure LDAP server is not enabled
  service:
    name: slapd
    state: stopped
    enabled: false

- name: 2.2.7 Ensure NFS and RPC are not enabled
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - rpcbind
    - nfs
    - nfs-server

- name: 2.2.8 Ensure DNS Server is not enabled
  service:
    name: named
    state: stopped
    enabled: false

- name: 2.2.9 Ensure FTP Server is not enabled
  service:
    name: vsftpd
    state: stopped
    enabled: false

- name: 2.2.10 Ensure HTTP server is not enabled
  service:
    name: httpd
    state: stopped
    enabled: false

- name: 2.2.11 Ensure IMAP and POP3 server is not enabled
  service:
    name: dovecot
    state: stopped
    enabled: false

- name: 2.2.12 Ensure Samba is not enabled
  service:
    name: smb
    state: stopped
    enabled: false

- name: 2.2.13 Ensure HTTP Proxy Server is not enabled
  service:
    name: squid
    state: stopped
    enabled: false

- name: 2.2.14 Ensure SNMP Server is not enabled
  service:
    name: snmpd
    state: stopped
    enabled: false

# 2.2.15 Ensure mail transfer agent is configured for local-only mode

- name: 2.2.16 Ensure NIS Server is not enabled
  service:
    name: ypserv
    state: stopped
    enabled: false

- name: 2.2.17 Ensure rsh server is not enabled
  service:
    name: {{ item }}
    state: stopped
    enabled: false
  loop:
    - rsh.socket
    - rlogin.socket
    - rexec.socket

- name: 2.2.18 Ensure telnet server is not enabled
  service:
    name: telnet.socket
    state: stopped
    enabled: false

- name: 2.2.19 Ensure tftp server is not enabled
  service:
    name: tftp.socket
    state: stopped
    enabled: false

- name: 2.2.20 Ensure rsync service is not enabled
  service:
    name: rsyncd
    state: stopped
    enabled: false

- name: 2.2.21 Ensure talk server is not enabled
  service:
    name: ntalk
    state: stopped
    enabled: false

## 2.3 Service Clients

- name: 2.3.1 Ensure NIS Client is not installed
  yum:
    pkg: ypbind
    state: absent

- name: 2.3.2 Ensure rsh client is not installed
  yum:
    pkg: rsh
    state: absent

- name: 2.3.3 Ensure talk client is not installed
  yum:
    pkg: talk
    state: absent

- name: 2.3.4 Ensure telnet client is not installed 
  yum:
    pkg: telnet
    state: absent

- name: 2.3.5 Ensure LDAP client is not installed
  yum:
    pkg: openldap-clients
    state: absent
