---

- name: Hello!
  debug:
    msg: "Hello world!"

## 3.1 Network Parameters (Host Only)

# 3.1.1 Ensure IP forwarding is disabled

# 3.1.2 Ensure packet redirect sending is disabled

## 3.2 Network Parameters (Host and Router)
# 3.2.1 Ensure source routed packets are not accepted

# 3.2.2 Ensure ICMP redirects are not accepted

# 3.2.3 Ensure secure ICMP redirects are not accepted

# 3.2.4 Ensure suspicious packets are logged

# 3.2.5 Ensure broadcast ICMP requests are ignored

# 3.2.6 Ensure bogus ICMP responses are ignored

# 3.2.7 Ensure Reverse Path Filtering is enabled

# 3.2.8 Ensure TCP SYN Cookies is enabled

## 3.3 IPv6 (If enabled use these, otherwise disable totally)

## 3.4 TCP Wrappers
# 3.4.1 Ensure TCP Wrappers is installed

# 3.4.2 Ensure /etc/hosts.allow is configured

# 3.4.3 Ensure /etc/hosts.deny is configured

# 3.4.4 Ensure permissions on /etc/hosts.allow are configured

## 3.5 Uncommon Network Protocols